services:
  alpine:
    command:
    - sleep
    - '20'
    environment:
      TEST: ter
    image: "alpine:latest"
  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: user
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: user
    image: "postgres:9.5"
version: '3.9'
