services:
  alpine:
    command: sleep 20
    environment:
      TEST: ter
    healthcheck:
      interval: 10s
      retries: 5
      test: echo Test
      timeout: 5s
    image: "alpine:latest"
  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: user
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: user
    image: "postgres:9.5"
  "test-service":
    build: '.'
version: '3.9'
