services:
  alpine:
    command:
    - sleep
    - '20'
    environment:
      TEST: ter
    healthcheck:
      interval: 10s
      retries: 5
      test:
      - echo
      - test
      timeout: 5s
    image: "alpine:latest"
version: '3.9'
